name: Traveler
favicon: null
layout_spectrum: 0.10626697586849332
typography_spectrum: 0.758658709237352
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8727453842293471
  lightness: 0.8205917812883854
  saturation: 0.8324882350862026
  rhythmicContrast: 0.021725665777921677
purpose: []
